version: 2.1

jobs:
  build: # this can be any name you choose
    docker:
      - image: node:16
    resource_class: large
    parallelism: 10

    steps:
      - checkout
      - restore_cache:
          name: Restore pnpm Package Cache
          keys:
            - pnpm-packages-{{ checksum "api/pnpm-lock.yaml" }}
      - run:
          name: Install pnpm package manager
          command: |
            curl -L https://pnpm.js.org/pnpm.js | node - add --global pnpm@7
      - run:
          name: Install Dependencies
          command: |
            cd api
            pnpm install
      - save_cache:
          name: Save pnpm Package Cache
          key: pnpm-packages-{{ checksum "api/pnpm-lock.yaml" }}
          paths:
            - api/node_modules
      - persist_to_workspace:
          paths:
            - "api"
          root: project
      

  test: # this can be any name you choose
    docker:
      - image: node:16
    resource_class: large
    parallelism: 10

    steps:
      - run:
          name: Install pnpm package manager
          command: |
            curl -L https://pnpm.js.org/pnpm.js | node - add --global pnpm@7
      - run:
          name: test app
          command: pnpm test

workflows:
    build:
      jobs:
        - build:
            filters:
              branches:
                only:
                  - circleci
        - test:
            requires:
              - build