apiVersion : apps/v1
kind: Deployment
metadata:
  name: "jokeapp"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "jokeapp"
  template:
    metadata:
      labels:
        app: "jokeapp"
    spec:
      containers:
        - name: "jokeapp"
          image: "mohammaddocker/joke-api:latest"
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "80"
          ports:
          - containerPort: 80