apiVersion: v1
kind: Service
metadata:
    name: "jokeapp-c62b"
    labels:
        app: "jokeapp-c62b"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "jokeapp-c62b"