---
 - hosts: all
   tasks:
   - name: Clone a github repository
     git:
       repo: https://github.com/mohammadbnei/cd-intro-tp.git
       dest: /home/mohammad/app
       clone: yes
       update: yes