name: Azure VM Update

on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
      - completed
  push:
    branches: ["main"]
    paths:
        - ".github/workflows/azure-vm-deploy.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: kielabokkie/ssh-key-and-known-hosts-action@v1
        with:
          ssh-private-key: ${{ secrets.AZURE_SSH_KEY }}
          ssh-host: ${{secrets.AZURE_VM_IP}}

      - name: Install docker and docker compose
        uses: dawidd6/action-ansible-playbook@v2
        with:
          # Required, playbook filepath
          playbook: main.yml
          # Optional, directory where playbooks live
          directory: ./ansible/docker
          # Optional, SSH private key
          key: ${{secrets.AZURE_SSH_KEY}}
          # Optional, literal inventory file contents
          inventory: |
            [azure-vm]
            ${{secrets.AZURE_VM_IP}} ansible_user=mohammad

            [azure_vm:vars]
            ansible_python_interpreter=/usr/bin/python3

      - name: Update docker compose image
        uses: dawidd6/action-ansible-playbook@v2
        with:
          # Required, playbook filepath
          playbook: azure-vm-update.yml
          # Optional, directory where playbooks live
          directory: ./ansible
          # Optional, SSH private key
          key: ${{secrets.AZURE_SSH_KEY}}
          # Optional, literal inventory file contents
          inventory: |
            [all]
            ${{secrets.AZURE_VM_IP}} ansible_user=mohammad

            [azure_vm:vars]
            ansible_python_interpreter=/usr/bin/python3
