name: Azure VM Update

on:
  push:
    branches: ["raspberry"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: kielabokkie/ssh-key-and-known-hosts-action@v1
        with:
          ssh-private-key: ${{ secrets.RASP_SSH_KEY }}
          ssh-host: ${{secrets.RASP_IP}}

      - name: Update docker compose image
        uses: dawidd6/action-ansible-playbook@v2
        with:
          # Required, playbook filepath
          playbook: azure-vm-update.yml
          # Optional, directory where playbooks live
          directory: ./ansible
          # Optional, SSH private key
          key: ${{secrets.RASP_SSH_KEY}}
          # Optional, literal inventory file contents
          inventory: |
            [all]
            ${{secrets.RASP_IP}}:2222 ansible_user=mohammad

            [azure_vm:vars]
            ansible_python_interpreter=/usr/bin/python3
