name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./api

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
          cache-dependency-path: api/package-lock.json

      - run: npm ci
      - run: npm run build --if-present
      - run: npm test

  build:
    needs: test

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./api

    steps:
      - uses: actions/checkout@v3

      - name: Get the latest tag
        id: get_version
        uses: battila7/get-version-action@v2

      - name: Echo version
        run: echo ${{ steps.get_version.outputs.version-without-v }}

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag joke-api:${{steps.get_version.outputs.version-without-v}}
