name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

env:
  workdir: api
  AZURE_WEBAPP_NAME: joke-app' # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: "api" # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: "16"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: pnpm/action-setup@v2.0.1
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7

      - name: Install dependencies
        run: pnpm install

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Unit Tests
        run: pnpm test

      - name: Build app
        run: pnpm build

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - run: ls

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: api/release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    environment:
      name: "production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app
      
      - name: unzip artifact for deployment
        run: unzip release.zip 

      - name: "Deploy to Azure Web App"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "joke-app"
          slot-name: "production"
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_350284e279874bcb865d8a539ddda65a }}
          package: .
